/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

#include "ahmissile.h"

int main (int argc, char *argv[])
{
	GtkWidget *MainWindow;
	int err;

#ifdef ENABLE_NLS
	bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
	textdomain (GETTEXT_PACKAGE);
#endif

	gtk_set_locale ();
	gtk_init (&argc, &argv);

	add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

	/* initialize the usb device */
	err = ahmissile_init();

	if (err) {
		MainWindow = create_NoDevDlg();
	} else {
		MainWindow = create_MainWindow ();
	}

	if (!ahmissile_supports_diag()) {
		/* hide diagonal movement buttons */
		GtkWidget *btn;

		btn = lookup_widget(MainWindow, "buttonUpLeft");
		gtk_widget_hide(btn);

		btn = lookup_widget(MainWindow, "buttonUpRight");
		gtk_widget_hide(btn);

		btn = lookup_widget(MainWindow, "buttonDownLeft");
		gtk_widget_hide(btn);

		btn = lookup_widget(MainWindow, "buttonDownRight");
		gtk_widget_hide(btn);
	}

	gtk_widget_show (MainWindow);

	gtk_main ();
	return 0;
}

